version: "2"
services:
    mongo:
        image: mongo:latest
        restart: on-failure
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./mondodb:/data/db
        ports:
          - '27017:27017'
